Se simplifico el nombre del archivo a test

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,46 +1,29 @@
 #!/bin/bash
 
-lastfilename_file="aux-data/last-test-name"
-
-# Verificar si se proporcionó un nombre de archivo como argumento
-if [ $# -eq 0 ]; then
-    echo "Uso: $0 <nombre_del_archivo>"
+# Verificar que se haya proporcionado un argumento
+if [ -z "$1" ]; then
+    echo "Uso: test archivo.cpp"
     exit 1
 fi
 
-# Verificar si el archivo dado existe
-if [ ! -f "$1" ]; then
-    echo "El archivo $1 no existe."
-    exit 1
+# Nombre del archivo cpp proporcionado
+archivo="$1"
+# Nombre del ejecutable generado (sin la extensión .cpp)
+ejecutable="${archivo%.*}"
+
+# Compilar y construir el proyecto utilizando CMake
+mkdir -p build
+cd build
+cmake -DArchivo="$archivo" .. > /dev/null
+make > /dev/null
+
+# Verificar si la compilación fue exitosa
+if [ $? -eq 0 ]; then
+    # Ejecutar el ejecutable generado
+    echo "Ejecutando..."
+    echo
+    "./$ejecutable"
+    echo
+else
+    echo "Error al compilar $archivo"
 fi
-
-# Verificar si existe un archivo de caché
-if [ -f "$lastfilename_file" ]; then
-    filename=$(cat "$lastfilename_file")
-    if [ -f "$filename" ]; then
-        # Cambiar el nombre del archivo ejecutable en CMakeLists.txt
-        sed -i "s#$filename#$1#g" CMakeLists.txt
-        echo "Se ha cambiado el archivo ejecutable de CMake a $filename."
-
-        # Compila con cmake y lo ejecuta
-        echo Ejecutando CMake...
-        cmake -B build
-        cd build
-
-        echo Compilando con Make...
-        make
-
-        echo Ejecutando el programa...
-
-        echo
-        ./main
-        echo
-
-        cd ..
-        exit 0
-    else
-        echo "El archivo $filename guardado en el caché ya no existe."
-    fi
-fi
-
-echo "No se encontró un archivo válido en el caché."
